#!/usr/bin/env bash
# Qyne — Full Bootstrap Script
#
# Deploys the entire Qyne stack on a fresh Ubuntu 24.04 VPS.
# Run this once on a new server. It is idempotent — safe to re-run.
#
# What it does:
#   1. System setup (Docker, Coolify, Tailscale, fail2ban)
#   2. Generates passwords and creates .env
#   3. Starts infrastructure (PostgreSQL x3, Redis, Prefect)
#   4. Runs database migrations (schema, RLS, roles, hardening)
#   5. Creates application DB role (qyne_app) with password
#   6. Sets up automated backups (cron)
#   7. Applies security hardening
#   8. Copies Traefik routing configs
#
# Usage:
#   git clone https://github.com/aikapenelope/novaincs.git
#   cd novaincs
#   sudo bash infra/bootstrap.sh
#
# After this script completes, you need to:
#   1. Run 'tailscale up' to authenticate with your Tailscale network
#   2. Open Coolify at http://<tailscale-ip>:8000 and create admin account
#   3. Connect GitHub in Coolify
#   4. Create two apps in Coolify (API + Dashboard) pointing to this repo
#   5. Set environment variables in Coolify for each app (printed at the end)
#   6. Configure DNS (A records for your domain)
#   7. Set Clerk keys in Coolify (from https://dashboard.clerk.com)
#
# Requirements:
#   - Ubuntu 24.04 LTS
#   - Root access
#   - Ports 22, 80, 443 open

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
NOVA_DIR="/opt/nova"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[bootstrap]${NC} $1"; }
warn() { echo -e "${YELLOW}[bootstrap]${NC} $1"; }
err()  { echo -e "${RED}[bootstrap]${NC} $1" >&2; }
info() { echo -e "${CYAN}[bootstrap]${NC} $1"; }

# --- Preflight ---
if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root (use sudo)."
    exit 1
fi

if ! grep -qi "ubuntu" /etc/os-release 2>/dev/null; then
    warn "This script is designed for Ubuntu 24.04. Proceed with caution."
fi

log "Starting Qyne bootstrap..."
log "Repo directory: $REPO_DIR"

# =========================================================================
# Step 1: System setup
# =========================================================================
log "Step 1/8: System setup..."

apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq curl jq unattended-upgrades fail2ban openssl > /dev/null

# Docker
if command -v docker &> /dev/null; then
    log "  Docker already installed: $(docker --version)"
else
    log "  Installing Docker..."
    curl -fsSL https://get.docker.com | sh
fi

# Tailscale
if command -v tailscale &> /dev/null; then
    log "  Tailscale already installed"
else
    log "  Installing Tailscale..."
    curl -fsSL https://tailscale.com/install.sh | sh
fi

# Coolify
if docker ps --format '{{.Names}}' 2>/dev/null | grep -q coolify; then
    log "  Coolify already running"
else
    log "  Installing Coolify..."
    curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
fi

# =========================================================================
# Step 2: Generate passwords and create .env
# =========================================================================
log "Step 2/8: Generating passwords..."

mkdir -p "$NOVA_DIR"

ENV_FILE="$NOVA_DIR/.env"

if [ -f "$ENV_FILE" ]; then
    log "  .env already exists at $ENV_FILE — skipping generation"
    log "  To regenerate, delete $ENV_FILE and re-run this script"
else
    PG_NOVA_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)
    PG_NOVA_APP_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)
    PG_AGNO_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)
    PG_PREFECT_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)
    REDIS_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)

    cat > "$ENV_FILE" << EOF
# Qyne Infrastructure — Generated by bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit this file. Keep it safe.

# PostgreSQL (pg-nova)
PG_NOVA_PASSWORD=$PG_NOVA_PASSWORD
PG_NOVA_APP_PASSWORD=$PG_NOVA_APP_PASSWORD

# PostgreSQL (pg-agno)
PG_AGNO_PASSWORD=$PG_AGNO_PASSWORD

# PostgreSQL (pg-prefect)
PG_PREFECT_PASSWORD=$PG_PREFECT_PASSWORD

# Redis
REDIS_PASSWORD=$REDIS_PASSWORD
EOF

    chmod 600 "$ENV_FILE"
    log "  Generated passwords and saved to $ENV_FILE"
fi

# Source the .env to use passwords in subsequent steps.
set -a
source "$ENV_FILE"
set +a

# =========================================================================
# Step 3: Start infrastructure containers
# =========================================================================
log "Step 3/8: Starting infrastructure..."

# Create data directories.
mkdir -p /var/lib/nova/pg-nova
mkdir -p /var/lib/nova/pg-agno
mkdir -p /var/lib/nova/backups

# Copy compose file and support scripts.
cp "$SCRIPT_DIR/docker-compose.infra.yml" "$NOVA_DIR/docker-compose.yml"
cp "$SCRIPT_DIR/prefect-start.sh" "$NOVA_DIR/prefect-start.sh"
cp "$SCRIPT_DIR/prefect-healthcheck.py" "$NOVA_DIR/prefect-healthcheck.py"
cp "$SCRIPT_DIR/backup.sh" "$NOVA_DIR/backup.sh"
chmod +x "$NOVA_DIR/prefect-start.sh" "$NOVA_DIR/backup.sh"

cd "$NOVA_DIR"
docker compose up -d

# Wait for PostgreSQL to be healthy.
log "  Waiting for pg-nova to be healthy..."
for i in $(seq 1 30); do
    if docker exec pg-nova pg_isready -U nova -q 2>/dev/null; then
        log "  pg-nova is ready"
        break
    fi
    if [ "$i" -eq 30 ]; then
        err "pg-nova did not become healthy in 30 seconds"
        exit 1
    fi
    sleep 1
done

# =========================================================================
# Step 4: Run database migrations
# =========================================================================
log "Step 4/8: Running database migrations..."

MIGRATION_DIR="$REPO_DIR/apps/api/drizzle"

for sql_file in "$MIGRATION_DIR"/0*.sql; do
    filename=$(basename "$sql_file")
    log "  Applying $filename..."
    docker exec -i pg-nova psql -U nova -d nova < "$sql_file" 2>&1 | grep -v "^$" | head -5
done

log "  All migrations applied"

# =========================================================================
# Step 5: Create application DB role
# =========================================================================
log "Step 5/8: Creating qyne_app role..."

docker exec -i pg-nova psql -U nova -d nova << EOSQL
-- Set password for qyne_app (created by migration 0002).
ALTER ROLE qyne_app PASSWORD '${PG_NOVA_APP_PASSWORD}';

-- Set password for qyne_readonly if it exists.
DO \$\$
BEGIN
    IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'qyne_readonly') THEN
        ALTER ROLE qyne_readonly PASSWORD '${PG_NOVA_APP_PASSWORD}';
    END IF;
END
\$\$;

-- Verify roles.
SELECT rolname, rolcanlogin, rolsuper FROM pg_roles
WHERE rolname IN ('qyne_app', 'qyne_readonly', 'nova_readonly');
EOSQL

log "  qyne_app role configured with password"

# =========================================================================
# Step 6: Set up automated backups
# =========================================================================
log "Step 6/8: Setting up backup cron..."

CRON_LINE_NOVA="0 3 * * * $NOVA_DIR/backup.sh pg-nova >> /var/log/nova-backup.log 2>&1"
CRON_LINE_AGNO="30 3 * * 0 $NOVA_DIR/backup.sh pg-agno >> /var/log/nova-backup.log 2>&1"
CRON_COMMENT="# Qyne PostgreSQL backups"

# Add cron entries if they don't already exist.
(crontab -l 2>/dev/null || true) | grep -q "backup.sh pg-nova" || {
    (crontab -l 2>/dev/null || true; echo "$CRON_LINE_NOVA"; echo "$CRON_LINE_AGNO"; echo "$CRON_COMMENT") | crontab -
    log "  Backup cron installed"
}

# =========================================================================
# Step 7: Security hardening
# =========================================================================
log "Step 7/8: Applying security hardening..."

bash "$SCRIPT_DIR/harden.sh"

# =========================================================================
# Step 8: Traefik routing configs
# =========================================================================
log "Step 8/8: Copying Traefik configs..."

TRAEFIK_DIR="/data/coolify/proxy/dynamic"
if [ -d "$TRAEFIK_DIR" ]; then
    cp "$SCRIPT_DIR/traefik-dynamic/"*.yaml "$TRAEFIK_DIR/"
    log "  Traefik configs copied to $TRAEFIK_DIR"
else
    warn "  Traefik dynamic dir not found. Copy configs manually after Coolify starts."
fi

# =========================================================================
# Summary
# =========================================================================
SERVER_IP=$(curl -4s --connect-timeout 5 https://ifconfig.io 2>/dev/null || echo "unknown")
TAILSCALE_IP=$(tailscale ip -4 2>/dev/null || echo "not configured — run 'tailscale up'")

echo ""
log "========================================="
log "  Qyne bootstrap complete"
log "========================================="
echo ""
info "Server IP:       $SERVER_IP"
info "Tailscale IP:    $TAILSCALE_IP"
info "Coolify UI:      http://$TAILSCALE_IP:8000"
info "Data directory:  /var/lib/nova"
info "Passwords file:  $ENV_FILE"
echo ""
log "Infrastructure running:"
docker compose ps --format "  {{.Name}}: {{.Status}}" 2>/dev/null
echo ""
log "Next steps:"
echo ""
echo "  1. Authenticate Tailscale:"
echo "     tailscale up"
echo ""
echo "  2. Open Coolify and create admin account:"
echo "     http://<tailscale-ip>:8000"
echo ""
echo "  3. In Coolify, connect GitHub and create two apps:"
echo ""
echo "     App 1: API"
echo "       - Repository: aikapenelope/novaincs"
echo "       - Branch: main"
echo "       - Build pack: Dockerfile"
echo "       - Dockerfile: apps/api/Dockerfile"
echo "       - Domain: api.yourdomain.com"
echo "       - Environment variables:"
echo "           DATABASE_URL=postgresql://qyne_app:${PG_NOVA_APP_PASSWORD}@pg-nova:5432/nova"
echo "           MIGRATION_DATABASE_URL=postgresql://nova:${PG_NOVA_PASSWORD}@pg-nova:5432/nova"
echo "           REDIS_URL=redis://:${REDIS_PASSWORD}@nova-redis:6379/0"
echo "           CLERK_SECRET_KEY=<from Clerk dashboard>"
echo "           CLERK_PUBLISHABLE_KEY=<from Clerk dashboard>"
echo "           CORS_ORIGINS=https://app.yourdomain.com,https://yourdomain.com"
echo "           R2_ACCESS_KEY_ID=<from Cloudflare>"
echo "           R2_SECRET_ACCESS_KEY=<from Cloudflare>"
echo "           R2_ENDPOINT=<from Cloudflare>"
echo "           R2_BUCKET=qyne-images"
echo "           R2_PUBLIC_URL=<from Cloudflare>"
echo "           FAL_KEY=<from fal.ai>"
echo "           NODE_ENV=production"
echo "           PORT=3000"
echo ""
echo "     App 2: Dashboard"
echo "       - Repository: aikapenelope/novaincs"
echo "       - Branch: main"
echo "       - Build pack: Dockerfile"
echo "       - Dockerfile: apps/dashboard/Dockerfile"
echo "       - Domain: app.yourdomain.com"
echo "       - Environment variables:"
echo "           NUXT_PUBLIC_API_URL=https://api.yourdomain.com"
echo "           NUXT_PUBLIC_CLERK_PUBLISHABLE_KEY=<from Clerk dashboard>"
echo "           NUXT_CLERK_SECRET_KEY=<from Clerk dashboard>"
echo "           NODE_ENV=production"
echo "           PORT=3001"
echo ""
echo "  4. In Coolify, enable for both apps:"
echo "     - Consistent Container Name: ON"
echo "     - Auto Deploy: ON"
echo "     - Force HTTPS: ON"
echo ""
echo "  5. Update Traefik configs with your container names:"
echo "     Edit /data/coolify/proxy/dynamic/qyne-api.yaml"
echo "     Edit /data/coolify/proxy/dynamic/qyne-dashboard.yaml"
echo "     Replace container names with the ones Coolify assigns."
echo ""
echo "  6. Configure DNS (A records pointing to $SERVER_IP):"
echo "     api.yourdomain.com  -> $SERVER_IP"
echo "     app.yourdomain.com  -> $SERVER_IP"
echo ""
echo "  7. Set up Clerk at https://dashboard.clerk.com"
echo "     Create an application, get the publishable + secret keys."
echo ""
