import {
  pgTable,
  uuid,
  varchar,
  text,
  boolean,
  jsonb,
  timestamp,
  index,
} from "drizzle-orm/pg-core";
import { tenants } from "./tenants.js";

/**
 * Feed items — AI-generated action cards for the merchant's dashboard.
 *
 * Generated by a BullMQ cron worker every 30 minutes. Each card represents
 * an insight or suggested action based on CRM, RFM, orders, and inventory data.
 *
 * Types:
 *   - at_risk_customer: "Maria hasn't bought in 15 days"
 *   - pending_payments: "3 payments waiting for verification"
 *   - low_stock: "Camisa Polo has only 2 units left"
 *   - new_customer: "New customer: Juan (from order #0051)"
 *   - cart_abandoned: "Anonymous visitor abandoned cart 4 hours ago"
 *   - daily_summary: "Yesterday: $120 in sales, 5 orders"
 *   - milestone: "You reached 50 customers!"
 */
export const feedItems = pgTable(
  "feed_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    type: varchar("type", { length: 50 }).notNull(),
    // Priority: critical > high > medium > low (for sorting)
    priority: varchar("priority", { length: 20 }).notNull().default("medium"),
    title: varchar("title", { length: 255 }).notNull(),
    body: text("body"),
    // Optional link to a related entity (customer, order, product)
    entityType: varchar("entity_type", { length: 50 }),
    entityId: uuid("entity_id"),
    // Action the merchant can take (e.g., "Verificar pago", "Contactar cliente")
    actionLabel: varchar("action_label", { length: 100 }),
    actionUrl: varchar("action_url", { length: 500 }),
    // State management
    isRead: boolean("is_read").notNull().default(false),
    isDismissed: boolean("is_dismissed").notNull().default(false),
    // Extra data for rendering (e.g., customer name, product image, amount)
    data: jsonb("data").notNull().default({}),
    // Deduplication key — prevents the same insight from being generated twice.
    // Format: "{type}:{entityId}:{date}" e.g. "at_risk_customer:uuid:2026-05-17"
    dedupeKey: varchar("dedupe_key", { length: 255 }),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("feed_items_tenant_idx").on(t.tenantId),
    index("feed_items_tenant_read_idx").on(t.tenantId, t.isRead),
    index("feed_items_tenant_created_idx").on(t.tenantId, t.createdAt),
    index("feed_items_dedupe_idx").on(t.tenantId, t.dedupeKey),
    index("feed_items_expires_idx").on(t.expiresAt),
  ],
);

/**
 * Notifications — real-time alerts triggered by specific events.
 *
 * Unlike feed items (generated periodically by a cron), notifications are
 * created immediately when an event occurs (new order, payment verified,
 * low stock threshold crossed).
 *
 * The dashboard polls GET /notifications every 30 seconds and shows a
 * bell icon with unread count + dropdown panel.
 *
 * Types:
 *   - new_order: "Nuevo pedido #0052 de Maria ($25.00)"
 *   - payment_verified: "Pago verificado para pedido #0051"
 *   - payment_uploaded: "Capture de pago recibido para #0050"
 *   - low_stock: "Camisa Polo: solo quedan 2 unidades"
 *   - order_expired: "Pedido #0049 expirado — stock liberado"
 *   - new_customer: "Nuevo cliente: Juan Rodriguez"
 */
export const notifications = pgTable(
  "notifications",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    type: varchar("type", { length: 50 }).notNull(),
    title: varchar("title", { length: 255 }).notNull(),
    body: text("body"),
    // Link to navigate when clicked
    actionUrl: varchar("action_url", { length: 500 }),
    // Related entity for grouping/deduplication
    entityType: varchar("entity_type", { length: 50 }),
    entityId: uuid("entity_id"),
    isRead: boolean("is_read").notNull().default(false),
    data: jsonb("data").notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("notifications_tenant_idx").on(t.tenantId),
    index("notifications_tenant_read_idx").on(t.tenantId, t.isRead),
    index("notifications_tenant_created_idx").on(t.tenantId, t.createdAt),
  ],
);
